AllCops:
  Exclude:
    - db/**/*
    - lib/tasks/**/*
    - config/**/*
Rails:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/BlockComments:
  Enabled: false
