# PostgreSQL
# Configure Using Gemfile
# gem 'pg'
#
development:
  adapter: postgresql
  encoding: unicode
  database: crm_db_development
  pool: 5
  username: ubuntu
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: 
  pool: 5
  username: ubuntu
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['APP_DATABASE_NAME'] %>
  pool: 5
  username: <%= ENV['APP_DATABASE_USER'] %>
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>